### ISSUE TITLE
instant crash on kitkat on startup

### ISSUE THREAD

**Issue by dpadgett** [dpadgett/Timer#7]

**Comment by dpadgett** [comment]
caused by a SecurityException when fetching the list of ringtones.  new build requires a special permission to read things from SD card, and the built-in way of finding ringtones throws the exception proactively since ringtones may be added via SD card.  workaround is to read them only out of the system dir, and add in manually the URI for the default ringtone.  (i am guessing it's ok for that to be on SD card, though i haven't tested it)

**Comment by nsteinbach** [comment]
So where exactly do the custom ringtones have to be located, either on the internal or external SD card, when the phone is running KitKat? I have not been able to make the app find my ringtones, with the exception of the default ringtone that is set in the Clock/Alarm app that comes from the phone manufacturer. Since I like this app better for countdown timers though, I'd be happy to be able to use it again with my own choice of ringtones...

**Comment by dpadgett** [comment]
android k+ does not provide an api to access them without having full access to the full sd card so i am not very comfortable putting it back in.
